name: Yggdrasil for HAOS
version: "0.2.3"
slug: haosygg
description: Yggdrasil mesh network addon for Home Assistant OS
url: "https://github.com/Alpherie/haosygg"
arch:
  - armv7
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: False
apparmor: true
host_network: true
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
