name: Yggdrasil for HAOS
version: "0.1.3"
slug: haosygg
description: Yggdrasil mesh network addon for Home Assistant OS
url: "https://github.com/Alpherie/haosygg"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - type: addon_config
    read_only: false
  - type: share
    read_only: False
startup: services
host_network: true
privileged:
  - NET_ADMIN
  - NET_RAW
